### ISSUE TITLE
Uncaught RangeError when navigating through the calendar

### ISSUE THREAD

**Issue by myusome** [MME-Aufgaben-im-Sommer-2022/mme-ss22-team-10#45]
**Bug User Story**
I want to be able to go through all my notes (no matter how old they are), so that I can recall my past and reflect, without the app stopping at some point.

**To Reproduce**
1. click multiple times back on the calendar

**Expected behavior**
the note keeps loading and the calendar changes if I want to go one month back/ahead

**Errorstack:**
```
observable-slim.js:149 Uncaught RangeError: Maximum call stack size exceeded
    at Object.get (observable-slim.js:149:9)
    at Calendar.getEntryData (Calendar.ts:118:12)
    at Calendar.getEntriesForMonth (Calendar.ts:92:40)
    at Calendar.checkEntries (Calendar.ts:144:14)
    at Calendar.getEntriesForMonth (Calendar.ts:102:10)
    at Calendar.checkEntries (Calendar.ts:144:14)
    at Calendar.getEntriesForMonth (Calendar.ts:102:10)
    at Calendar.checkEntries (Calendar.ts:144:14)
    at Calendar.getEntriesForMonth (Calendar.ts:102:10)
    at Calendar.checkEntries (Calendar.ts:144:14)
```

**Comment by myusome** [comment]
solved with https://github.com/MME-Aufgaben-im-Sommer-2022/mme-ss22-team-10/pull/44

there now is another bug
